### ISSUE TITLE
手机上的音量控制条有点反人类啊

### ISSUE THREAD

**Issue by evarainy** [Copay/cPlayer#14]
大佬，手机上的音量控制条有点反人类啊 = = 改成垂直调节的更好吧，水平的经常拖动的时候页面也动了

**Comment by Copay** [comment]
嗯...我看看

**Comment by Copay** [comment]
手机操作确实有点那啥...音量操作在电脑上是hover悬浮出现音量控制条,手机貌似也不好模拟悬浮...水平拖动时页面也动的话我看看能不能禁止一下

**Comment by evarainy** [comment]
个人建议 PC上的音频插件还是比较完善了，但是移动端的却没有太好的播放器；移动端已经是大势所趋，大佬为何不考虑专门针对移动端做优化，做个世界上最好的移动端音乐插件呢XD~ = =

**Comment by Copay** [comment]
@evarainy THANKS😂I'm trying hard to improve.

**Comment by lwl12** [comment]
@evarainy 做不来，这个违反广告法了

**Comment by Copay** [comment]
摇滚b

evarainy <notifications@github.com>编写：



个人建议 PC上的音频插件还是比较完善了，但是移动端的却没有太好的播放器；移动端已经是大势所趋，大佬为何不考虑专门针对移动端做优化，做个世界上最好的移动端音乐插件呢XD~ = =

―

**Comment by Copay** [comment]
尤其

evarainy <notifications@github.com>编写：



个人建议 PC上的音频插件还是比较完善了，但是移动端的却没有太好的播放器；移动端已经是大势所趋，大佬为何不考虑专门针对移动端做优化，做个世界上最好的移动端音乐插件呢XD~ = =

―

**Comment by Copay** [comment]
evarainy <notifications@github.com>编写：



个人建议 PC上的音频插件还是比较完善了，但是移动端的却没有太好的播放器；移动端已经是大势所趋，大佬为何不考虑专门针对移动端做优化，做个世界上最好的移动端音乐插件呢XD~ = =

―

**Comment by Copay** [comment]
bd6e6da

**Comment by Copay** [comment]
点击音量按钮出现音量条，再点击就消失。

在屏幕宽度小于600px时适用
以及请无视小圆圈，那玩意不对touch*事件做出反应。（一头晕直接push上去，忘记隐藏了）
