### ISSUE TITLE
Android Chrome 通知栏中的播放暂停按钮无效

### ISSUE THREAD

**Issue by journey-ad** [Copay/cPlayer#19]
系统：Android 7.1.2
浏览器：Chrome Canary 62.0.3194.0
cPlayer 版本：目前 [demo](https://cplayer.js.org) 页中所用的版本

另外是否考虑添加 Media Session API 支持？
[相关介绍](https://developers.google.com/web/updates/2017/02/media-session)

**Comment by EYHN** [comment]
![image](https://user-images.githubusercontent.com/13579374/29699894-d720b2d2-8992-11e7-9a5f-d4f4070fcd33.png)
https://github.com/MoePlayer/cPlayer/commit/22abb44e6f8f4379bce473e271c1cccede31cd61
