### ISSUE TITLE
许可证问题

### ISSUE THREAD

**Issue by ClassicOldSong** [Copay/cPlayer#2]
cPlayer使用了GPL许可证而cPlayer-Typecho-Plugin使用了MIT许可证
希望cPlayer能改用MIT

**Comment by Copay** [comment]
w 听说Typecho用的GPLv2 https://github.com/typecho/typecho/blob/master/license.txt

**Comment by Copay** [comment]
算了GPL太长没看懂恩就换换换成MIT好了

**Comment by ClassicOldSong** [comment]
OK~
