### ISSUE TITLE
Uncaught TypeError: parseInt(...).toString(...).padStart is not a function

### ISSUE THREAD

**Issue by Lucilor** [Copay/cPlayer#27]
请教各位大佬，这个错误怎么解决?
![qq 20180316144939](https://user-images.githubusercontent.com/12553377/37507405-481442ca-2929-11e8-8ee9-cc351c83b650.jpg)
![qq 20180316145046](https://user-images.githubusercontent.com/12553377/37507468-90983042-2929-11e8-829e-bcc4487f94a5.jpg)

**Comment by EYHN** [comment]
请问你的浏览器版本？

**Comment by Lucilor** [comment]
换台电脑又没问题了……
