### ISSUE TITLE
这个是解码音频流来播放的吗？

### ISSUE THREAD

**Issue by qylcx7758** [Copay/cPlayer#29]
但是不通过web-audio-api是怎样实现的呢？不知道有没有理解错，谢谢高手！

**Comment by Copay** [comment]
并不是哦
这个是audio标签的封装
Web Audio API可以对音频操作,但是在这里并没有涉及到.
并且Web Audio API 有跨域问题.

**Comment by qylcx7758** [comment]
噢噢，注意到了，谢谢
