### ISSUE TITLE
播放不了网易云的资源

### ISSUE THREAD

**Issue by wbq-bios** [Copay/cPlayer#30]
在你们官方的demo中添加网易云的资源能显示却无法播放 报错 Uncaught (in promise) DOMException: Failed to load because no supported source was found.

**Comment by wbq-bios** [comment]
歌曲id 569212270

**Comment by EYHN** [comment]
Thank you!

After my test, this should be the error of 163 Music API, not the problem of cPlayer.
I will pay attention and try to fix it.
