### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by lyricsbd** [Copay/cPlayer#31]
When I use This Its not working.How Config this?
<div id="app"></div>

<script src="https://cdn.jsdelivr.net/gh/MoePlayer/cPlayer/dist/cplayer.js"></script>
<script>
  let player = new cplayer({
    element: document.getElementById('app'),
    playlist: [
      {
        src: '歌曲资源链接...',
        poster: '封面链接...',
        name: '歌曲名称...',
        artist: '歌手名称...',
        lyric: '歌词...',
        sublyric: '副歌词，一般为翻译...'
      },
      {
        ...
      },
      ......
    ]
  })
</script>

**Comment by Copay** [comment]
@lyricsbd please give us a demo in jsfiddle or else.

**Comment by lyricsbd** [comment]
@Copay here  https://jsfiddle.net/yc02vsa6/

**Comment by Copay** [comment]
@lyricsbd thanks, now I am working with it.

**Comment by lyricsbd** [comment]
please bro solve it @Copay  
thanks :) advance

**Comment by Copay** [comment]
@lyricsbd try this https://jsfiddle.net/czq7wbd0/

**Comment by lyricsbd** [comment]
its just  play as mp3 not video.mp4  demo  大图暗黑样式 https://cplayer.js.org/

**Comment by Copay** [comment]
@lyricsbd Maybe you'd better look through the readme.

**Comment by lyricsbd** [comment]
Thanks Bro I also used your aplayer its awesome if you add download button ;) & add musicmatch api for lyrics 💃

**Comment by Copay** [comment]
@lyricsbd I am sorry but I have to say the aplayer is diygod's, not mine.

**Comment by lyricsbd** [comment]
is cplayer  yours?  bro @Copay

**Comment by Copay** [comment]
@lyricsbd The current version is made by EYHN

**Comment by lyricsbd** [comment]
can i use this cplayer likes as ? bro

`<div class="aplayer"
    data-name="rainymood"
    data-artist="rainymood"
    data-url="https://moeplayer.b0.upaiyun.com/aplayer/hikarunara.mp3"
    data-cover="https://rainymood.com/i/badge.jpg"
   data-lrc="[00:00.00]APlayer\n[00:04.01]is\n[00:08.02]amazing">
   </div>`

**Comment by Copay** [comment]
@lyricsbd sorry you can't

**Comment by EYHN** [comment]
https://github.com/MoePlayer/cPlayer/issues/32
