### ISSUE TITLE
__SELF__的问题

### ISSUE THREAD

**Issue by ghost** [Copay/cPlayer#5]
感觉你用**SELF**的地方都可以换成this，后面看了下，所有用的地方都是箭头函数啊

**Comment by Copay** [comment]
确实，不过由于习惯问题，就没改

**Comment by Copay** [comment]
我看看。。。不清楚Babel会不会对箭头函数处理，所以加了个self。既然babel把箭头函数处理成了普通函数，我打算在下一次更新中修正。
